### PR TITLE
adding context manager to azure test case

### PR DESCRIPTION
**Pull request by Mohannadcse**
To fix the issue https://github.com/langroid/langroid/issues/233

If this solution satisfactory, then we can move the test cases to the main

### CODE REVIEW

**Review by pchalasani — CHANGES_REQUESTED** [review]
the ctx mgr can be more generally useful, so it should be under `language_models/`

**Comment by Mohannadcse** [comment]
Sure, Do you have a specific thought? I'd love to hear it and take it into account.

**Comment by pchalasani** [comment]
I am thinking about the best way to support model famlies. For the env vars, we should be leveraging grouped env vars like how I did for `llama2`. I'm still making changes to that. Let's hold on this until then.

**Comment by Mohannadcse** [comment]
This issue is already solved via client the new OpenAI API

**Pull request closed without merging**
