### PR TITLE
I/O Abstraction; Websockets; JS Webpage Chat

### PR DESCRIPTION
**Pull request by AshishHoodaIITD**

### CODE REVIEW

**Comment by Mohannadcse** [comment]
I followed the instructions in `README` under `examples/chat_webpage/nodejs-chat-app`

image

I have an empty page from the browser after opening the link `http://localhost:3000/`, is this expected? or am I missing anything?

image

**Comment by AshishHoodaIITD** [comment]
@Mohannadcse I have resolved the above issue. Please pull the updated code and give it another try.

**Comment by Mohannadcse** [comment]
This is what I have now, asked 2 questions but answers weren't displayed 

image

**Comment by Mohannadcse** [comment]
Works now after running `python3 examples/basic/chat_websockets.py` besides `npm run dev`

**Comment by Mohannadcse** [comment]
@pchalasani @AshishHoodaIITD do you think context manager should be implemented here to decide where the output should be forwarded?

**Comment by pchalasani** [comment]
Closing for now, will revisit when we are ready.

**Pull request closed without merging**
