### PR TITLE
QOL & multi-dialect support

### PR DESCRIPTION
**Pull request by rithwikbabu**
Capable of querying all dialects supported by SqlAlchemy:
- SQLite
- PostgreSQL
- MySQL
- Oracle
- Microsoft SQL Server
- Firebird
- Sybase

Potentially fixed bug causing agent to begin with a sql query rather than a 'ready' message.

### CODE REVIEW

**Review by pchalasani — APPROVED** [review]

**Comment by pchalasani** [comment]
@rithwikbabu  is there some way to test/demonstrate PostgresSQL support?

**Comment by pchalasani** [comment]
And SQLite would also be interesting

**Comment by rithwikbabu** [comment]
> @rithwikbabu is there some way to test/demonstrate PostgresSQL support?

SQLite is already used in the existing tests. However, to test/use each of the other 6 types of dbs we would need to install the respective driver and host the db locally. This could be done using docker. Should I look into a way to implement this?

**Comment by pchalasani** [comment]
> > @rithwikbabu is there some way to test/demonstrate PostgresSQL support?
> 
> SQLite is already used in the existing tests. However, to test/use each of the other 6 types of dbs we would need to install the respective driver and host the db locally. This could be done using docker. Should I look into a way to implement this?

Rather not involve docker. Let's hold off for now.

**Pull request merged**
