### PR TITLE
adding PDF support

### PR DESCRIPTION
**Pull request by Mohannadcse**
I'll add the test case once we confirm with the changes, but it's already tested under `langroid-example`

### CODE REVIEW

**Comment by pchalasani** [comment]
I think it's better to add pdf-handling ability to `DocChatAgent`. I will take look tmr. In any case lint (ruff) is failing here. I don't know how the pre-commit hook allowed it.

**Review by pchalasani — CHANGES_REQUESTED** [review]
as discussed in conversation on main thread

**Comment by Mohannadcse** [comment]
My thought was to have a dedicated loader/parser for PDF and avoid overloading RepoLoader and URLLoader for future usage. But I am happy to work on that if you feel it's better to give DocChatAgent PDF handling capability.

**Comment by pchalasani** [comment]
Yes it’s best to expand the types of docs DocChatAgent can handle , so that a user of this class doesn’t need to change any code to handle pdfs

**Comment by Mohannadcse** [comment]
Sounds good, I'll make the necessary changes by tmro

**Review by pchalasani — APPROVED** [review]

**Pull request merged**
