### PR TITLE
allow updating chromadb version

### PR DESCRIPTION
**Pull request by Mohannadcse**
Addresses #396

### CODE REVIEW

**Comment by Mohannadcse** [comment]
Notes:
- I disabled the decorator `@retry_with_exponential_backoff` inside the callable class and solved the chroma problem. 
- The current errors are due to the absence of `hf-embeddings`. Shouldn't `hf-embeddings` be installed as part of Langroid, otherwise, the test cases should be under `extra`.

**Review by pchalasani — COMMENTED** [review]
@Mohannadcse  this looks good 

HF had an outage yesterday, that may be the reason for the hf-embed err

Also I restored the @retry decorator, and tests seem to pass. Let me know if you noticed some other issue.

**Comment by pchalasani** [comment]
> @Mohannadcse this looks good
> 
> HF had an outage yesterday, that may be the reason for the hf-embed err
> 
> Also I restored the @Retry decorator, and tests seem to pass. Let me know if you noticed some other issue.

never mind, I see the issue with the retry wrapper now. I had not updated the chroma version in my local.

**Comment by Mohannadcse** [comment]
I still need to fix these errors. Before pushing `make check` wasn't showing them, but I noticed them in my last push.

**Comment by Mohannadcse** [comment]
> ok . for the retry, use tenacity as shown here in example 1 https://platform.openai.com/docs/guides/rate-limits/error-mitigation?context=tier-free
> 
> inside the `__call__`, define a fn

I tried this suggestion but didn't work, was raising an error

**Pull request merged**
