### PR TITLE
feat: add support for Azure OpenAI Embeddings - 2

### PR DESCRIPTION
**Pull request by AbhishekRP2002**
this PR aims to close https://github.com/langroid/langroid/issues/514 serving as the second draft, post-closing the first draft #601 

https://github.com/langroid/langroid/commit/8d58d8afd3304434e4d098fa1ec22b35d5620ecc - commit reverting all changes  made wrt #530 

https://github.com/langroid/langroid/commit/224541351420fbe433fac2b5fbc55164fec6ad87 - commit addressing the naming changes as proposed by @pchalasani 

cc: @pchalasani 
pls lemme know if this PR looks good ? Apologies for the previous commit fault. will keep it in mind from now onwards

### CODE REVIEW

**Comment by pchalasani** [comment]
Thanks for fixing @AbhishekRP2002 , will look later this week

**Comment by pchalasani** [comment]
thanks @AbhishekRP2002 I am waiting to get azure credentials/quota to I can test it, and add the needed values to the github actions secrets (The Azure process is *horrendous* which is why I never bothered with this)

**Comment by AbhishekRP2002** [comment]
> thanks @AbhishekRP2002 I am waiting to get azure credentials/quota to I can test it, and add the needed values to the github actions secrets (The Azure process is *horrendous* which is why I never bothered with this)

I understand totally.Makes sense. 
Pls review and test at your convenience. 
I'll start working on Metaphor to Exa migration.

**Comment by pchalasani** [comment]
@AbhishekRP2002 I still haven't managed to get an Azure OpenAI access setup. Waiting on a msft rep for help.

**Comment by AbhishekRP2002** [comment]
> @AbhishekRP2002 I still haven't managed to get an Azure OpenAI access setup. Waiting on a msft rep for help.

sure. No worries. Would like to contribute more to the project post successful merge hopefully.

**Comment by pchalasani** [comment]
@AbhishekRP2002 I spent some time looking into this and got it working, but  there is overlap in the env settings between azure oai embedding and oai chat completion ( I think api key and endpoint), so to avoid duplication we should factor those out as AzureOpenAISettings field in the two respective Config classes.

I have modified your PR locally and push sometime today and then it should be fine

**Comment by AbhishekRP2002** [comment]
> @AbhishekRP2002 I spent some time looking into this and got it working, but there is overlap in the env settings between azure oai embedding and oai chat completion ( I think api key and endpoint), so to avoid duplication we should factor those out as AzureOpenAISettings field in the two respective Config classes.
> 
> I have modified your PR locally and push sometime today and then it should be fine

oh i see. apologies, i missed that completely.
Thanks for the refactoring, i will also take a look at it so that in future i keep these in mind.

**Comment by AbhishekRP2002** [comment]
hi @pchalasani  any updates on this ?

**Comment by pchalasani** [comment]
closing, superceded by #651

**Pull request closed without merging**
